// scripts/sync-tokens.mjs
// Bridges the synthesized design tokens (the single source of truth in
// reports/m3-token-synthesis/tokens/dist/) into the Next.js renderer.
//
// Run via `npm run sync:tokens` whenever the upstream tokens change.
//
// Outputs:
//   - app/_tokens.generated.css  : full copy of tokens.css (upstream canonical
//                                  CSS variables, unchanged), plus a Tailwind
//                                  v4 `@theme inline` block that re-exposes
//                                  every color/space/radius/font/shadow as
//                                  `var(--<upstream-name>)` so that Tailwind
//                                  utility classes (bg-primary, text-primary,
//                                  font-display, rounded-8, etc.) all resolve
//                                  through the canonical tokens. No hex
//                                  values are inlined into the @theme block.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const rendererRoot = resolve(here, "..");
const repoRoot = resolve(rendererRoot, "..");
// Token source is overridable so the renderer is not welded to one brand.
// WEB_DESIGNER_TOKENS_DIR is set by render_nextjs.py from its --tokens argument.
// Without this the renderer silently rendered every brand in the FIRST brand's
// palette — a bug only a second brand could reveal.
const tokenDir = process.env.WEB_DESIGNER_TOKENS_DIR
  ? resolve(process.env.WEB_DESIGNER_TOKENS_DIR, "tokens/dist")
  : resolve(repoRoot, "reports/m3-token-synthesis/tokens/dist");
const cssOut = resolve(rendererRoot, "app/_tokens.generated.css");
const jsonIn = resolve(tokenDir, "tailwind-tokens.json");
const cssIn = resolve(tokenDir, "tokens.css");

if (!existsSync(cssIn) || !existsSync(jsonIn)) {
  console.error(
    `[sync-tokens] Missing token files in ${tokenDir}.\n` +
      "Run skills/web-designer/scripts/synthesize_tokens.py first.",
  );
  process.exit(1);
}

const tokensJson = JSON.parse(readFileSync(jsonIn, "utf8"));
const tokensCss = readFileSync(cssIn, "utf8");

// tailwind-tokens.json uses v3 namespace names; Tailwind v4 expects v4
// namespaces. Translate the keys and emit a var(...) indirection so the
// canonical --color-* / --typography-* / --radius-* declarations stay the
// single source of truth.
const v3ToV4 = {
  colors: "color",
  fontFamily: "font",
  spacing: "spacing",
  borderRadius: "radius",
  boxShadow: "shadow",
};

function flatten(node, prefix, out) {
  if (typeof node !== "object" || node === null) return;
  for (const [k, v] of Object.entries(node)) {
    const next = [...prefix, k];
    if (typeof v === "string" || Array.isArray(v)) {
      out.push({ path: next, value: Array.isArray(v) ? v.join(", ") : v });
    } else if (typeof v === "object") {
      flatten(v, next, out);
    }
  }
}

const flatPaths = [];
flatten(tokensJson.theme?.extend ?? {}, [], flatPaths);

const themeLines = ["@theme inline {"];
for (const entry of flatPaths) {
  const { path, value } = entry;
  const [v3Namespace, ...rest] = path;
  const v4Namespace = v3ToV4[v3Namespace];
  if (!v4Namespace) continue; // skip unknown namespaces
  const v4Name = `${v4Namespace}-${rest.join("-")}`;
  // The canonical upstream variable uses --<v4-name> as well
  // (synthesize_tokens emits --color-primary, --typography-font-family-display,
  //  --radius-8, --spacing-8, --shadow-0). For fontFamily we need to map to
  // the upstream --typography-font-family-<name> var instead.
  // Tailwind v4 `@theme inline` must receive a RESOLVED value. Emitting
  // `--color-primary: var(--color-primary)` is self-referential, which CSS
  // treats as invalid at computed-value time — it silently wiped every colour
  // token (the gold signature dot rendered transparent). Font families still
  // indirect through the canonical --typography-* var because that name
  // differs from the theme key, so no cycle is possible there.
  if (v3Namespace === "fontFamily") {
    themeLines.push(`  --${v4Name}: var(--typography-font-family-${rest.join("-")});`);
  } else {
    themeLines.push(`  --${v4Name}: ${value};`);
  }
}
themeLines.push("}");

mkdirSync(dirname(cssOut), { recursive: true });
const header = `/**
 * GENERATED by scripts/sync-tokens.mjs — do not edit by hand.
 * Source: reports/m3-token-synthesis/tokens/dist/{tokens.css,tailwind-tokens.json}
 * Regenerate via: npm run sync:tokens
 */
`;
const generated = `${header}\n${tokensCss}\n\n/* === @theme inline bridge (drives Tailwind v4 utility classes) === */\n${themeLines.join("\n")}\n`;

writeFileSync(cssOut, generated, "utf8");
console.log(
  `[sync-tokens] Wrote ${cssOut} (${generated.length} bytes; ` +
    `${themeLines.length - 2} @theme entries).`,
);